import {renderStatusBadge} from '../components/status-badge.js';
import {renderEvidenceTrace} from '../components/evidence-trace.js';
import {renderReviewHubTabs} from './review.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function renderReportSelection({runs=[],t,locale,loading=false,view='reports'}){
  const items=Array.isArray(runs)?runs:[];
  return `<section class="report-selection"><header class="report-header"><div><p class="overview-eyebrow">${t('nav.reportsReview',{},locale)}</p><h1>${t('report.selectTitle',{},locale)}</h1></div></header>${renderReviewHubTabs(view,t,locale)}${loading?`<p role="status">${t('report.loading',{},locale)}</p>`:''}${items.length?`<ul class="report-run-list">${items.map(run=>`<li><button type="button" data-open-report-run="${esc(run.run_id)}"><span>${esc(run.research_question||run.project_id||run.run_id||t('common.unknown',{},locale))}</span>${renderStatusBadge(run.outcome||run.status,t,locale)}<small>${esc(run.run_id)}</small></button></li>`).join('')}</ul>`:`<div class="empty">${t(loading?'report.loading':'report.noReports',{},locale)}</div>`}</section>`;
}
export function renderReport({run,result,reportData,artifacts=[],t,locale,loading=false}){
  const sections=Array.isArray(reportData?.sections)?reportData.sections:[];
  const claims=Array.isArray(reportData?.claims)?reportData.claims:[];
  const evidence=Array.isArray(reportData?.evidence)?reportData.evidence:[];
  const bibliography=Array.isArray(reportData?.bibliography)?reportData.bibliography:[];
  const claimMap=new Map(claims.map(claim=>[claim.claim_id,claim]));
  const synthetic=run?.synthetic===true||result?.synthetic===true||reportData?.synthetic===true;
  const nav=sections.map((section,index)=>`<a href="#report-section-${index}">${esc(section.title||section.deliverable_type||t('common.unknown',{},locale))}</a>`).join('');
  const rendered=sections.map((section,index)=>{
    const claimIds=Array.isArray(section.claim_ids)?section.claim_ids:[];
    const bound=claimIds.map(id=>claimMap.get(id)).filter(Boolean);
    const missing=claimIds.filter(id=>!claimMap.has(id));
    return `<section id="report-section-${index}" class="report-section"><header><span class="report-section-type">${esc(section.deliverable_type||t('common.unknown',{},locale))}</span><h2>${esc(section.title||t('common.unknown',{},locale))}</h2></header><div class="report-prose" data-report-content="true">${esc(section.body||t('common.unknown',{},locale))}</div>${bound.length||missing.length?`<div class="report-section-claims"><h3>${t('report.evidenceBackedClaims',{},locale)}</h3>${bound.map((claim,claimIndex)=>`<article class="report-claim"><div class="report-claim-heading"><h4 title="${esc(claim.claim_id||'')}">${t('report.claimLabel',{number:claimIndex+1},locale)}</h4>${renderStatusBadge(claim.verification?.status||claim.verification||claim.status,t,locale)}</div><p data-report-content="true">${esc(claim.claim||claim.text||t('common.unknown',{},locale))}</p>${renderEvidenceTrace({claim,evidence,bibliography,t,locale})}</article>`).join('')}${missing.map(id=>`<p class="inspector-notice">${t('report.claimUnavailable',{id:esc(id)},locale)}</p>`).join('')}</div>`:''}</section>`;
  }).join('');
  const downloads=(Array.isArray(artifacts)?artifacts:[]).map(item=>{const id=item?.artifact_id||item?.id;return id?`<li>${esc(item.title||item.type||id)} · <a href="/api/v1/artifacts/${encodeURIComponent(id)}" download>${t('report.downloadArtifact',{},locale)}</a></li>`:''}).filter(Boolean);
  return `<article class="report-reader"><header class="report-header"><div><p class="overview-eyebrow">${t('nav.reportsReview',{},locale)}</p><h1>${esc(reportData?.research_question||run?.project_id||run?.run_id||t('common.unknown',{},locale))}</h1><p>${renderStatusBadge(result?.outcome||run?.outcome||run?.status,t,locale)}${synthetic?` <span class="badge partial">${t('investigation.synthetic',{},locale)}</span>`:''}</p></div><div class="report-actions"><button id="report-list">${t('report.chooseAnother',{},locale)}</button><button id="report-review-inbox">${t('review.inboxTab',{},locale)}</button><button id="reload-report">${t('report.reload',{},locale)}</button><button id="export-report" ${reportData?'':'disabled'}>${t('report.export',{},locale)}</button></div></header>${loading?`<p role="status">${t('report.loading',{},locale)}</p>`:''}${result?.conclusion?`<section class="report-conclusion"><h2>${t('report.outcome',{},locale)}</h2><p>${esc(result.conclusion)}</p></section>`:''}${nav?`<nav class="report-toc" aria-label="${t('report.contents',{},locale)}">${nav}</nav>`:''}${rendered||`<div class="empty">${t('report.noSections',{},locale)}</div>`}${downloads.length?`<section class="report-downloads"><h2>${t('report.downloads',{},locale)}</h2><ul>${downloads.join('')}</ul></section>`:''}<details class="inspector-advanced report-technical"><summary>${t('evidence.advanced',{},locale)}</summary><dl><dt>run_id</dt><dd>${esc(run?.run_id||t('common.unknown',{},locale))}</dd><dt>outcome</dt><dd>${esc(result?.outcome||run?.outcome||t('common.unknown',{},locale))}</dd><dt>claim ids</dt><dd><code>${esc(claims.map(claim=>claim.claim_id||t('common.unknown',{},locale)).join(', '))}</code></dd></dl></details></article>`;
}
