import {renderStatusBadge} from '../components/status-badge.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const shown=(value,t,locale)=>value==null||value===''?t('common.unknown',{},locale):String(value);

export function renderReviewHubTabs(view,t,locale){
  return `<nav class="review-hub-tabs" aria-label="${t('review.hubLabel',{},locale)}"><button type="button" data-review-hub="reports" aria-current="${view==='reports'?'page':'false'}">${t('review.reportsTab',{},locale)}</button><button type="button" data-review-hub="inbox" aria-current="${view==='inbox'?'page':'false'}">${t('review.inboxTab',{},locale)}</button></nav>`;
}

export function renderReviewInbox({items=[],unavailableRuns=[],next=null,loading=false,t,locale}){
  const entries=Array.isArray(items)?items:[];
  const unavailable=Array.isArray(unavailableRuns)?unavailableRuns:[];
  const content=entries.length?`<ul class="review-inbox-list">${entries.map(item=>`<li><article class="review-inbox-item"><header><strong>${esc(shown(item.title||item.code,t,locale))}</strong>${renderStatusBadge(item.status,t,locale)}<span class="review-read-only">${t('review.readOnly',{},locale)}</span></header><p>${esc(shown(item.message||item.reason,t,locale))}</p><dl><dt>${t('review.runStatus',{},locale)}</dt><dd>${renderStatusBadge(item.run_status,t,locale)}</dd><dt>${t('review.outcome',{},locale)}</dt><dd>${renderStatusBadge(item.outcome,t,locale)}</dd><dt>${t('review.document',{},locale)}</dt><dd>${esc(shown(item.document_id,t,locale))}</dd><dt>${t('review.source',{},locale)}</dt><dd>${esc(shown(item.source,t,locale))}</dd><dt>${t('review.impact',{},locale)}</dt><dd>${esc(shown(item.impact,t,locale))}</dd></dl><button type="button" data-review-open-run="${esc(item.run_id||'')}">${t('review.openInvestigation',{},locale)}</button><details class="review-identifiers"><summary>${t('evidence.advanced',{},locale)}</summary><dl><dt>run_id</dt><dd><code>${esc(shown(item.run_id,t,locale))}</code></dd><dt>issue_id</dt><dd><code>${esc(shown(item.issue_id,t,locale))}</code></dd><dt>kind</dt><dd><code>${esc(shown(item.kind,t,locale))}</code></dd><dt>actionable</dt><dd><code>${String(item.actionable===false?false:item.actionable)}</code></dd><dt>decision_actions</dt><dd><code>${esc(JSON.stringify(Array.isArray(item.decision_actions)?item.decision_actions:null))}</code></dd><dt>issue_index</dt><dd><code>${esc(shown(item.issue_index,t,locale))}</code></dd></dl></details></article></li>`).join('')}</ul>`:`<div class="empty" role="status">${t(loading?'review.loading':'review.noIssues',{},locale)}</div>`;
  const unknownRuns=unavailable.length?`<section class="review-unavailable"><h2>${t('review.unavailableTitle',{},locale)}</h2><p>${t('review.unavailableDescription',{},locale)}</p><ul>${unavailable.map(run=>`<li><code>${esc(shown(run.run_id,t,locale))}</code> · ${t('review.issueCountUnknown',{},locale)}</li>`).join('')}</ul></section>`:'';
  return `<section class="review-inbox"><header class="report-header"><div><p class="overview-eyebrow">${t('nav.reportsReview',{},locale)}</p><h1>${t('review.inboxTitle',{},locale)}</h1><p class="review-limit-note">${t('review.scopeNote',{},locale)}</p></div>${loading?`<span role="status">${t('review.loading',{},locale)}</span>`:''}</header>${renderReviewHubTabs('inbox',t,locale)}<p class="review-monitor-note">${t('review.monitorNote',{},locale)} <button type="button" data-open-monitor-reviews>${t('review.openMonitorRoute',{},locale)}</button></p>${content}${unknownRuns}${next?`<button id="review-inbox-more" type="button" ${loading?'disabled':''}>${t('review.more',{},locale)}</button>`:''}</section>`;
}
